language: cpp
compiler: gcc
dist: trusty

env:
  - CODECOV_TOKEN="b4485777-b359-4ad5-81d8-665c6035d730"
  
before_install:
  # C++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++11
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

script:
  - ./regressiontests.sh
  - ./get_coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  