#!/usr/bin/python3

from matplotlib import pyplot as plt
from numpy import genfromtxt
import numpy

# read in data generated by get_columns_and_widths.cpp
#data = genfromtxt("recursive_size_longlists.txt", delimiter=',')
data = genfromtxt("recursive_size.txt", delimiter=',')

# variables from data
listnumbers = data[:,0]
lengths = data[:,1]
non_rec = data[:,2]
depth1 = data[:,3]
depth2 = data[:,4]
numselectors = data[:,5]
payloadsize = data[:,6]

#plt.plot(lengths, non_rec, 'o')
#plt.plot(lengths, depth1, 'o')
#plt.plot(lengths, depth2, 'o')
#plt.xlabel('list length')

plt.plot(payloadsize, non_rec, 'o')
plt.plot(payloadsize, depth1, 'o')
plt.plot(payloadsize, depth2, 'o')
plt.xlabel('payload size (bytes)')

#plt.plot(numselectors, non_rec, 'o')
#plt.plot(numselectors, depth1, 'o')
#plt.plot(numselectors, depth2, 'o')
#plt.xlabel('number of selectors')

plt.ylabel('total compressed size (bytes)')
plt.legend(['non recursive','depth 1','depth 2'])
plt.show()

