#!/usr/bin/python3

from matplotlib import pyplot as plt
from numpy import genfromtxt
import numpy

# read in data generated by get_columns_and_widths.cpp
data = genfromtxt("num_unique_widths_vs_mean_columns.txt", delimiter=',')

# variables from data
listnumbers = data[:,0]
lengths = data[:,1]
mean_num_columns = data[:,2]
num_unique_column_widths = data[:,3]

# find indices of short and long lists
ind_short = numpy.where(lengths < 100)
ind_long = numpy.where(lengths >= 100)

# get values for short and long lists
shortuniq = num_unique_column_widths[ind_short]
shortmeancols = mean_num_columns[ind_short]
longuniq = num_unique_column_widths[ind_long]
longmeancols = mean_num_columns[ind_long]

# manually add values for limit lines
widths = list()
for i in range(1,11) :
    widths.append(i)

eightbitlimit = list()
eightbitlimit.append(8)
eightbitlimit.append(8)
eightbitlimit.append(4)
eightbitlimit.append(4)
eightbitlimit.append(2)
eightbitlimit.append(2)
eightbitlimit.append(2)
eightbitlimit.append(2)
eightbitlimit.append(2)
eightbitlimit.append(2)

sixteenbitlimit = list()
sixteenbitlimit.append(16)
sixteenbitlimit.append(16)
sixteenbitlimit.append(8)
sixteenbitlimit.append(8)
sixteenbitlimit.append(5)
sixteenbitlimit.append(5)
sixteenbitlimit.append(5)
sixteenbitlimit.append(5)
sixteenbitlimit.append(4)
sixteenbitlimit.append(4)

thirtytwo = list()
thirtytwo.append(32)
thirtytwo.append(32)
thirtytwo.append(16)
thirtytwo.append(16)
thirtytwo.append(10)
thirtytwo.append(10)
thirtytwo.append(10)
thirtytwo.append(10)
thirtytwo.append(8)
thirtytwo.append(8)

# plot the data
plt.plot(shortuniq, shortmeancols, 'o')
plt.plot(longuniq, longmeancols, 'o')
plt.plot(widths, eightbitlimit)
plt.plot(widths, sixteenbitlimit)
plt.plot(widths, thirtytwo)

plt.xlabel('number of unique column widths')
plt.ylabel('mean number of columns per word')
plt.legend(['short lists (<100)', 'long lists (>10,000)', '8bit limit','16bit limit', '32bit limit'])

plt.show()
